@WebhookSystem_HostAddress = http://localhost:5000

### Create a Webhook Subscription
POST {{WebhookSystem_HostAddress}}/webhooks/subscriptions
Content-Type: application/json
{
  "webhookUrl": "",
  "eventType": "order.created"
}

### Get Orders
Get {{WebhookSystem_HostAddress}}/orders
Accept: application/json

### Create an Order
POST {{WebhookSystem_HostAddress}}/orders
Content-Type: application/json
{
  "customerName": "John Doe",
  "amount": 1000
}